# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6fb5cce33eb5bd8ff929d59ea6367c23"
name = "nerd-limit"
application_url = "https://tb-advise-retention-presentations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1cce8422.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tb-advise-retention-presentations.trycloudflare.com/auth/callback",
  "https://tb-advise-retention-presentations.trycloudflare.com/auth/shopify/callback",
  "https://tb-advise-retention-presentations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
